### ISSUE TITLE
Proper steps 

### ISSUE THREAD

**Issue by anush97** [shreyaspapi/licence-plate-recognition-python-opencv#1]
Hi, your readme doesnt show the flow of running the files of the github repository like which file to run first and so on.

if we directly have to run main.py:

video1.mp4
Traceback (most recent call last):
  File "main.py", line 154, in <module>
    main()
  File "main.py", line 59, in main
    imgOriginalScene  = cv2.imread(video_feed(video_input))  # open image
  File "main.py", line 30, in video_feed
    gray = cv2.cvtColor(frames, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

I am experiencing this error

**Comment by gyanendrapandey11799** [comment]
if we directly have to run main.py:

video1.mp4
Traceback (most recent call last):
File "main.py", line 154, in
main()
File "main.py", line 59, in main
imgOriginalScene = cv2.imread(video_feed(video_input)) # open image
File "main.py", line 30, in video_feed
gray = cv2.cvtColor(frames, cv2.COLOR_BGR2GRAY)
cv2.error: OpenCV(4.1.2) C:\projects\opencv-python\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'

same error

**Comment by shreyaspapi** [comment]
This happens when the video.mp4 is not present or there is version mismatch with opencv.
